parser: babel-eslint

globals:
  require: true
  process: true
  Promise: true
  module: true
  console: true

rules:
  semi: error
  no-undef: error
  eol-last: warn
  comma-dangle:
    - warn
    - always-multiline
